version: "3"

services:
  api:
    build: .
    container_name: express-typescript-api
    restart: always
    networks:
      - proxy
    expose:
      - "3101"

networks:
  proxy:
    external: true
    name: nginx-proxy-manager_default
